v = int(input('Digite um valor para ver sua tabuada:'))
print('_' * 15)
print('{} x {:2} = {} \n{} x {:2} = {}'.format(v, 1, v*1, v, 2, v*2))
print('{} x {:2} = {} \n{} x {:2} = {}'.format(v, 3, v*3, v, 4, v*4))
print('{} x {:2} = {} \n{} x {:2} = {}'.format(v, 5, v*5, v, 6, v*6 ))
print('{} x {:2} = {} \n{} x {:2} = {}'.format(v, 7, v*7, v, 8, v*8))
print('{} x {:2} = {} \n{} x {:2} = {}'.format(v, 9, v*9, v, 10, v*10,))
print('_' * 15)
